addSbtPlugin("org.lyranthe.sbt" % "partial-unification"  % "1.1.2")
addSbtPlugin("io.spray"         % "sbt-revolver"         % "0.9.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"  % "1.3.25")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.4.2")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.10")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"         % "3.8.1")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"              % "2.0.0")
